#log_level:
is_debug: False
log_level: "INFO"
log_path: "log/tensorboard_log/ernie_matching"

#training_args:
train_batch_size: 24
eval_batch_size: 24
learning_rate: 0.00002
num_train_epochs: 8
early_stop_patience: 3

lr_scheduler_type: "linear" # "linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"
warmup_ratio: 0.1
#num_warmup_steps: 100
gradient_accumulation_steps: 1
max_grad_norm: 1.0
weight_decay: 0.01
eval_every_number_of_epoch: 1

accelerator_params:
  fp16: True
do_adv: False
adv_name: "word_embeddings"
adv_epsilon: 1.0

# data args:
preprocessing_num_workers: null
pad_to_max_length: False
overwrite_cache: False

#model args:
#num_labels: 11
max_length: 128
dropout: 0.1

pre_train_tokenizer: "model/language_model/ernie-gram"
pre_train_model: "model/language_model/ernie-gram"

# output model path
output_dir: "model/tmp/ernie_matching"

train_data_dir: "data/sort/train_pairwise.csv"
dev_data_dir: "data/sort/dev_pairwise.csv"