# log level
is_debug: Fasle
log_level: "INFO"

# training args
train_batch_size: 32
eval_batch_size: 4
lr_scheduler_type: "linear"
num_warmup_steps: 0
gradient_accumulation_steps: 1
weight_decay: 0.01
learning_rate: 0.00005
num_train_epochs: 20
eval_every_number_of_epoch: 1
early_stop_patience: 5

# model args
num_labels: 302
max_len: 512
dropout: 0.1
feature_dim: 128

pre_train_tokenizer: "model/language_model/chinese-roberta-wwm-ext/"
pre_train_model: "model/language_model/lawformer"

train_data_path: "data/fyt_train_use_data/CAIL-Long/civil/train.json"
dev_data_path: "data/fyt_train_use_data/CAIL-Long/civil/dev.json"
test_data_path: "data/fyt_train_use_data/CAIL-Long/civil/test.json"

label_mapping_path: "data/fyt_train_use_data/CAIL-Long/civil/label_mapping.csv"

# output model path
output_dir: "model/ThuLawsCls/"