LogArguments:
  is_debug: True
  log_level: "DEBUG"

TrainingArguments:
  train_batch_size: 32
  eval_batch_size: 4
  lr_scheduler_type: "linear"
  learning_rate: 0.00005
  num_train_epochs: 20
  accelerator_params:
    fp16: True

ModelArguments:
  model_name_or_path: ''

DataTrainingArguments:
  embedding_path: ""
  dataset: "data/bxh_search_data/textCNN"
  train_data_path: "data/bxh_search_data/textCNN/train_dev/train/train.json"
  dev_data_path: "data/bxh_search_data/textCNN/train_dev/dev/dev.json"
  test_data_path: ""
  output_dir: "model/bxh_search_model/textCNN/"
  max_length: 512