LogArguments:
  is_debug: True
  log_level: "DEBUG"

TrainingArguments:
  train_batch_size: 32
  eval_batch_size: 4
  lr_scheduler_type: "linear"
  learning_rate: 0.00005
  num_train_epochs: 4
  accelerator_params:
    fp16: True

ModelArguments:
  model_name_or_path: 'model/language_model/bert-base-chinese'

DataTrainingArguments:
  train_data_path: "data/fyt_train_use_data/QA/pro_qa.csv"
  dev_data_path: "data/fyt_train_use_data/QA/pro_qa.csv"
  test_data_path: "data/fyt_train_use_data/QA/pro_qa.csv"
  output_dir: "/home/fyt/model/similarity_model/query_cls"
  max_length: 128