# log level
is_debug: False

# training args
train_batch_size: 32
eval_batch_size: 8
lr_scheduler_type: "linear"
num_warmup_steps: 0
gradient_accumulation_steps: 1
weight_decay: 0.01
learning_rate: 0.00002
num_train_epochs: 20
eval_every_number_of_epoch: 1
early_stop_patience: 20

# model args
num_labels: 202
max_len: 512
dropout: 0.1
feature_dim: 128

pre_train_tokenizer: "model/language_model/chinese-roberta-wwm-ext"
pre_train_model: "model/language_model/lawformer"

train_data_path: "data/CAIL/2018/CAIL2018_ALL_DATA/final_all_data/exercise_contest/data_train.json"
dev_data_path: "data/CAIL/2018/CAIL2018_ALL_DATA/final_all_data/exercise_contest/data_valid.json"
test_data_path: "data/CAIL/2018/CAIL2018_ALL_DATA/final_all_data/exercise_contest/data_test.json"

label_mapping_path: "data/CAIL/2018/CAIL2018_ALL_DATA/final_all_data/exercise_contest/label_mapping.csv"

# output model path
output_dir: "model/LawformerCls_freeze/"