log_level: "INFO"

tokenizer: "../../model/language_model/chinese-roberta-wwm-ext"
model: "../../model/language_model/chinese-roberta-wwm-ext"
task_model: "../../model/cls_onnx_model/jiufen_model.onnx"

num_labels: 14
task_name: "suqiu_cls"

threshold: 0.8 # 如果概率高于阈值，则使用正则表达式检查，是否存在该诉求

label_mapping_path: "Config/jiufen.csv"

batch_size: 16
max_len: 512