log_level: "INFO"

tokenizer: "/home/fyt/model/marriage_bert/confirm_invalid/final"
model: "/home/fyt/model/marriage_bert/confirm_invalid/final"

test_data_path: "/home/fyt/data/fyt_train_use_data/CAIL-Long/civil/test.json"
label_mapping_path: "/home/fyt/huangyulin/project/fyt/LawEntityExtraction/data/bert/confirm_invalid/confirm_invalid.csv"

batch_size: 16
max_len: 128