log_level: "INFO"

tokenizer: "../../model/language_model/chinese-roberta-wwm-ext"
model: "../../model/language_model/chinese-roberta-wwm-ext"
task_model: "../../model/cls_onnx_model/situ_model.onnx"

num_labels: 229
task_name: "situa_cls"

threshold: 0.8 # 如果概率高于阈值，则使用正则表达式检查，是否存在该诉求，若有，则输出，若无，则输出空

label_mapping_path: "../LabelClsReview/Config/loan_and_marriage.csv"

batch_size: 16
max_len: 512